wget "http://subdev.portolancs.intra/portowiki/images/ID_diesel_loco_CC_201-05_060327_4217_kta.jpg" -O "IDdiesellocoCC201-050603274217kta.jpg"
wget "http://subdev.portolancs.intra/portowiki/images/台灣高鐵-一般列車停靠於桃園站南下月台.JPG" -O "-.JPG"
wget "http://subdev.portolancs.intra/portowiki/images/Railroad" -O "Railroad"
wget "http://subdev.portolancs.intra/portowiki/images/ID_diesel_loco_CC_204-06_060403_2512_mri.jpg" -O "IDdiesellocoCC204-060604032512mri.jpg"
wget "http://subdev.portolancs.intra/portowiki/images/Diesel_locomotive.JPG" -O "Diesellocomotive.JPG"
wget "http://subdev.portolancs.intra/portowiki/images/Deviatkino-Ruchi" -O "Deviatkino-Ruchi"
wget "http://subdev.portolancs.intra/portowiki/images/Aikan-shuttle.JPG" -O "Aikan-shuttle.JPG"
wget "http://subdev.portolancs.intra/portowiki/images/E5" -O "E5"
wget "http://subdev.portolancs.intra/portowiki/images/MTR-EastRailLineTrain.jpg" -O "MTR-EastRailLineTrain.jpg"
wget "http://subdev.portolancs.intra/portowiki/images/4-6-0" -O "4-6-0"
wget "http://subdev.portolancs.intra/portowiki/images/Otloczyn" -O "Otloczyn"
wget "http://subdev.portolancs.intra/portowiki/images/Pioneer Zephyr meal service 1934.jpg" -O "PioneerZephyrmealservice1934.jpg"
wget "http://subdev.portolancs.intra/portowiki/images/DSBtrain.jpg" -O "DSBtrain.jpg"
wget "http://subdev.portolancs.intra/portowiki/images/Dentetsu" -O "Dentetsu"
wget "http://subdev.portolancs.intra/portowiki/images/TRA E1001 in Hualien Station 20070123.jpg" -O "TRAE1001inHualienStation20070123.jpg"
wget "http://subdev.portolancs.intra/portowiki/images/Tzarskoselskaya Railway - Watercolour.jpg" -O "TzarskoselskayaRailway-Watercolour.jpg"
wget "http://subdev.portolancs.intra/portowiki/images/BNSF 7663.jpg" -O "BNSF7663.jpg"
wget "http://subdev.portolancs.intra/portowiki/images/ER2-973" -O "ER2-973"
